#!/usr/bin/env python3
import json
import sys

# Dicionário de países (código -> {nome, alpha2})
countries = {
    "1": {"name": "Afghanistan", "alpha2": "AF"},
    "2": {"name": "Bahrain", "alpha2": "BH"},
    "3": {"name": "Bangladesh", "alpha2": "BD"},
    "4": {"name": "Bhutan", "alpha2": "BT"},
    "5": {"name": "Brunei Darussalam", "alpha2": "BN"},
    "6": {"name": "Cambodia", "alpha2": "KH"},
    "7": {"name": "China PR", "alpha2": "CN"},
    "8": {"name": "Hong Kong", "alpha2": "HK"},
    "9": {"name": "India", "alpha2": "IN"},
    "10": {"name": "Indonesia", "alpha2": "ID"},
    "11": {"name": "IR Iran", "alpha2": "IR"},
    "12": {"name": "Iraq", "alpha2": "IQ"},
    "13": {"name": "Japan", "alpha2": "JP"},
    "14": {"name": "Jordan", "alpha2": "JO"},
    "15": {"name": "Korea DPR", "alpha2": "KP"},
    "16": {"name": "Korea Republic", "alpha2": "KR"},
    "17": {"name": "Kuwait", "alpha2": "KW"},
    "18": {"name": "Laos", "alpha2": "LA"},
    "19": {"name": "Lebanon", "alpha2": "LB"},
    "20": {"name": "Macau", "alpha2": "MO"},
    "21": {"name": "Malaysia", "alpha2": "MY"},
    "22": {"name": "Maldives", "alpha2": "MV"},
    "23": {"name": "Mongolia", "alpha2": "MN"},
    "24": {"name": "Myanmar", "alpha2": "MM"},
    "25": {"name": "Nepal", "alpha2": "NP"},
    "26": {"name": "Oman", "alpha2": "OM"},
    "27": {"name": "Pakistan", "alpha2": "PK"},
    "28": {"name": "Palestine", "alpha2": "PS"},
    "29": {"name": "Philippines", "alpha2": "PH"},
    "30": {"name": "Qatar", "alpha2": "QA"},
    "31": {"name": "Saudi Arabia", "alpha2": "SA"},
    "32": {"name": "Singapore", "alpha2": "SG"},
    "33": {"name": "Sri Lanka", "alpha2": "LK"},
    "34": {"name": "Syria", "alpha2": "SY"},
    "36": {"name": "Thailand", "alpha2": "TH"},
    "37": {"name": "United Arab Emirates", "alpha2": "AE"},
    "38": {"name": "Vietnam", "alpha2": "VN"},
    "39": {"name": "Yemen", "alpha2": "YE"},
    "40": {"name": "Kyrgyz Republic", "alpha2": "KG"},
    "41": {"name": "Tajikistan", "alpha2": "TJ"},
    "42": {"name": "Turkmenistan", "alpha2": "TM"},
    "43": {"name": "Timor-Leste", "alpha2": "TL"},
    "44": {"name": "Algeria", "alpha2": "DZ"},
    "45": {"name": "Angola", "alpha2": "AO"},
    "46": {"name": "Benin", "alpha2": "BJ"},
    "47": {"name": "Botswana", "alpha2": "BW"},
    "48": {"name": "Burkina Faso", "alpha2": "BF"},
    "49": {"name": "Burundi", "alpha2": "BI"},
    "50": {"name": "Cameroon", "alpha2": "CM"},
    "51": {"name": "Cape Verde", "alpha2": "CV"},
    "52": {"name": "Central African Republic", "alpha2": "CF"},
    "53": {"name": "Chad", "alpha2": "TD"},
    "54": {"name": "Comoros", "alpha2": "KM"},
    "55": {"name": "Congo DR", "alpha2": "CD"},
    "56": {"name": "Côte d'Ivoire", "alpha2": "CI"},
    "57": {"name": "Djibouti", "alpha2": "DJ"},
    "58": {"name": "Egypt", "alpha2": "EG"},
    "59": {"name": "Equatorial Guinea", "alpha2": "GQ"},
    "60": {"name": "Eritrea", "alpha2": "ER"},
    "61": {"name": "Ethiopia", "alpha2": "ET"},
    "62": {"name": "Gabon", "alpha2": "GA"},
    "63": {"name": "Gambia", "alpha2": "GM"},
    "64": {"name": "Ghana", "alpha2": "GH"},
    "65": {"name": "Guinea", "alpha2": "GN"},
    "66": {"name": "Guinea-Bissau", "alpha2": "GW"},
    "67": {"name": "Kenya", "alpha2": "KE"},
    "68": {"name": "Lesotho", "alpha2": "LS"},
    "69": {"name": "Liberia", "alpha2": "LR"},
    "70": {"name": "Libya", "alpha2": "LY"},
    "71": {"name": "Madagascar", "alpha2": "MG"},
    "72": {"name": "Malawi", "alpha2": "MW"},
    "73": {"name": "Mali", "alpha2": "ML"},
    "74": {"name": "Mauritania", "alpha2": "MR"},
    "75": {"name": "Mauritius", "alpha2": "MU"},
    "76": {"name": "Morocco", "alpha2": "MA"},
    "77": {"name": "Mozambique", "alpha2": "MZ"},
    "78": {"name": "Namibia", "alpha2": "NA"},
    "79": {"name": "Niger", "alpha2": "NE"},
    "80": {"name": "Nigeria", "alpha2": "NG"},
    "81": {"name": "Rwanda", "alpha2": "RW"},
    "82": {"name": "São Tomé and Príncipe", "alpha2": "ST"},
    "83": {"name": "Senegal", "alpha2": "SN"},
    "84": {"name": "Seychelles", "alpha2": "SC"},
    "85": {"name": "Sierra Leone", "alpha2": "SL"},
    "86": {"name": "Somalia", "alpha2": "SO"},
    "87": {"name": "South Africa", "alpha2": "ZA"},
    "88": {"name": "Sudan", "alpha2": "SD"},
    "89": {"name": "Eswatini", "alpha2": "SZ"},
    "90": {"name": "Tanzania", "alpha2": "TZ"},
    "91": {"name": "Togo", "alpha2": "TG"},
    "92": {"name": "Tunisia", "alpha2": "TN"},
    "93": {"name": "Uganda", "alpha2": "UG"},
    "94": {"name": "Zambia", "alpha2": "ZM"},
    "95": {"name": "Zimbabwe", "alpha2": "ZW"},
    "98": {"name": "Congo", "alpha2": "CG"},
    "103": {"name": "Anguilla", "alpha2": "AI"},
    "104": {"name": "Antigua and Barbuda", "alpha2": "AG"},
    "105": {"name": "Aruba", "alpha2": "AW"},
    "106": {"name": "Bahamas", "alpha2": "BS"},
    "107": {"name": "Barbados", "alpha2": "BB"},
    "108": {"name": "Belize", "alpha2": "BZ"},
    "109": {"name": "Bermuda", "alpha2": "BM"},
    "110": {"name": "Canada", "alpha2": "CA"},
    "111": {"name": "Cayman Islands", "alpha2": "KY"},
    "112": {"name": "Costa Rica", "alpha2": "CR"},
    "113": {"name": "Cuba", "alpha2": "CU"},
    "114": {"name": "Dominica", "alpha2": "DM"},
    "115": {"name": "Dominican Republic", "alpha2": "DO"},
    "116": {"name": "El Salvador", "alpha2": "SV"},
    "117": {"name": "Grenada", "alpha2": "GD"},
    "119": {"name": "Guatemala", "alpha2": "GT"},
    "120": {"name": "Haiti", "alpha2": "HT"},
    "121": {"name": "Honduras", "alpha2": "HN"},
    "122": {"name": "Jamaica", "alpha2": "JM"},
    "124": {"name": "Mexico", "alpha2": "MX"},
    "125": {"name": "Montserrat", "alpha2": "MS"},
    "127": {"name": "Nicaragua", "alpha2": "NI"},
    "128": {"name": "Panama", "alpha2": "PA"},
    "129": {"name": "Puerto Rico", "alpha2": "PR"},
    "130": {"name": "Saint Kitts and Nevis", "alpha2": "KN"},
    "131": {"name": "Saint Lucia", "alpha2": "LC"},
    "132": {"name": "Saint Vincent and the Grenadines", "alpha2": "VC"},
    "133": {"name": "Trinidad and Tobago", "alpha2": "TT"},
    "134": {"name": "Turks and Caicos Islands", "alpha2": "TC"},
    "135": {"name": "USA", "alpha2": "US"},
    "136": {"name": "British Virgin Islands", "alpha2": "VG"},
    "137": {"name": "US Virgin Islands", "alpha2": "VI"},
    "138": {"name": "French Guiana", "alpha2": "GF"},
    "139": {"name": "Suriname", "alpha2": "SR"},
    "140": {"name": "Curaçao", "alpha2": "CW"},
    "144": {"name": "Argentina", "alpha2": "AR"},
    "145": {"name": "Bolivia", "alpha2": "BO"},
    "146": {"name": "Brazil", "alpha2": "BR"},
    "147": {"name": "Chile", "alpha2": "CL"},
    "148": {"name": "Colombia", "alpha2": "CO"},
    "149": {"name": "Ecuador", "alpha2": "EC"},
    "150": {"name": "Paraguay", "alpha2": "PY"},
    "151": {"name": "Peru", "alpha2": "PE"},
    "152": {"name": "Uruguay", "alpha2": "UY"},
    "153": {"name": "Venezuela", "alpha2": "VE"},
    "159": {"name": "Guyana", "alpha2": "GY"},
    "161": {"name": "American Samoa", "alpha2": "AS"},
    "162": {"name": "Australia", "alpha2": "AU"},
    "163": {"name": "Cook Islands", "alpha2": "CK"},
    "164": {"name": "Fiji", "alpha2": "FJ"},
    "165": {"name": "New Caledonia", "alpha2": "NC"},
    "166": {"name": "New Zealand", "alpha2": "NZ"},
    "167": {"name": "Papua New Guinea", "alpha2": "PG"},
    "168": {"name": "Samoa", "alpha2": "WS"},
    "169": {"name": "Solomon Islands", "alpha2": "SB"},
    "170": {"name": "Tahiti", "alpha2": "PF"},
    "171": {"name": "Tonga", "alpha2": "TO"},
    "172": {"name": "Vanuatu", "alpha2": "VU"},
    "176": {"name": "Guam", "alpha2": "GU"},
    "184": {"name": "Palau", "alpha2": "PW"},
    "189": {"name": "Israel", "alpha2": "IL"},
    "190": {"name": "Turkey", "alpha2": "TR"},
    "191": {"name": "Albania", "alpha2": "AL"},
    "192": {"name": "Andorra", "alpha2": "AD"},
    "193": {"name": "Armenia", "alpha2": "AM"},
    "194": {"name": "Austria", "alpha2": "AT"},
    "195": {"name": "Azerbaijan", "alpha2": "AZ"},
    "196": {"name": "Belarus", "alpha2": "BY"},
    "197": {"name": "Belgium", "alpha2": "BE"},
    "198": {"name": "Bosnia and Herzegovina", "alpha2": "BA"},
    "199": {"name": "Bulgaria", "alpha2": "BG"},
    "200": {"name": "Croatia", "alpha2": "HR"},
    "201": {"name": "Cyprus", "alpha2": "CY"},
    "202": {"name": "Czech Republic", "alpha2": "CZ"},
    "203": {"name": "Denmark", "alpha2": "DK"},
    "204": {"name": "England", "alpha2": "GB-ENG"},
    "205": {"name": "Estonia", "alpha2": "EE"},
    "206": {"name": "Faroe Islands", "alpha2": "FO"},
    "207": {"name": "Finland", "alpha2": "FI"},
    "208": {"name": "France", "alpha2": "FR"},
    "209": {"name": "Georgia", "alpha2": "GE"},
    "210": {"name": "Germany", "alpha2": "DE"},
    "211": {"name": "Greece", "alpha2": "GR"},
    "212": {"name": "Hungary", "alpha2": "HU"},
    "213": {"name": "Iceland", "alpha2": "IS"},
    "214": {"name": "Republic of Ireland", "alpha2": "IE"},
    "215": {"name": "Italy", "alpha2": "IT"},
    "216": {"name": "Kazakhstan", "alpha2": "KZ"},
    "217": {"name": "Latvia", "alpha2": "LV"},
    "218": {"name": "Liechtenstein", "alpha2": "LI"},
    "219": {"name": "Lithuania", "alpha2": "LT"},
    "220": {"name": "Luxembourg", "alpha2": "LU"},
    "221": {"name": "North Macedonia", "alpha2": "MK"},
    "222": {"name": "Malta", "alpha2": "MT"},
    "223": {"name": "Moldova", "alpha2": "MD"},
    "224": {"name": "Netherlands", "alpha2": "NL"},
    "225": {"name": "Northern Ireland", "alpha2": "GB-NIR"},
    "226": {"name": "Norway", "alpha2": "NO"},
    "227": {"name": "Poland", "alpha2": "PL"},
    "228": {"name": "Portugal", "alpha2": "PT"},
    "229": {"name": "Romania", "alpha2": "RO"},
    "230": {"name": "Russia", "alpha2": "RU"},
    "231": {"name": "San Marino", "alpha2": "SM"},
    "232": {"name": "Scotland", "alpha2": "GB-SCT"},
    "234": {"name": "Slovakia", "alpha2": "SK"},
    "235": {"name": "Slovenia", "alpha2": "SI"},
    "236": {"name": "Spain", "alpha2": "ES"},
    "237": {"name": "Sweden", "alpha2": "SE"},
    "238": {"name": "Switzerland", "alpha2": "CH"},
    "239": {"name": "Ukraine", "alpha2": "UA"},
    "240": {"name": "Uzbekistan", "alpha2": "UZ"},
    "241": {"name": "Wales", "alpha2": "GB-WLS"},
    "245": {"name": "Gibraltar", "alpha2": "GI"},
    "250": {"name": "Monaco", "alpha2": "MC"},
    "260": {"name": "- Others", "alpha2": None},
    "298": {"name": "Chinese Taipei", "alpha2": "TW"},
    "303": {"name": "Serbia", "alpha2": "RS"},
    "304": {"name": "Montenegro", "alpha2": "ME"},
    "311": {"name": "Kosovo", "alpha2": "XK"},
    "312": {"name": "South Sudan", "alpha2": "SS"},
    "99": {"name": "Mayotte", "alpha2": "YT"},
    "100": {"name": "Réunion", "alpha2": "RE"},
    "101": {"name": "Saint Helena", "alpha2": "SH"},
    "118": {"name": "Guadeloupe", "alpha2": "GP"},
    "123": {"name": "Martinique", "alpha2": "MQ"},
    "141": {"name": "Greenland", "alpha2": "GL"},
    "142": {"name": "Saint-Pierre and Miquelon", "alpha2": "PM"},
    "143": {"name": "United States Minor Outlying Islands", "alpha2": "UM"},
    "158": {"name": "Falkland Islands", "alpha2": "FK"},
    "160": {"name": "South Georgia and the South Sandwich Islands", "alpha2": "GS"},
    "173": {"name": "Christmas Island", "alpha2": "CX"},
    "174": {"name": "Cocos (Keeling) Islands", "alpha2": "CC"},
    "175": {"name": "French Polynesia", "alpha2": "PF"},
    "177": {"name": "Kiribati", "alpha2": "KI"},
    "178": {"name": "Micronesia", "alpha2": "FM"},
    "180": {"name": "Nauru", "alpha2": "NR"},
    "181": {"name": "Niue", "alpha2": "NU"},
    "182": {"name": "Norfolk Island", "alpha2": "NF"},
    "183": {"name": "Northern Mariana Islands", "alpha2": "MP"},
    "185": {"name": "Pitcairn Islands", "alpha2": "PN"},
    "186": {"name": "Tokelau", "alpha2": "TK"},
    "187": {"name": "Tuvalu", "alpha2": "TV"},
    "188": {"name": "Wallis and Futuna", "alpha2": "WF"},
    "242": {"name": "Åland Islands", "alpha2": "AX"},
    "247": {"name": "Guernsey", "alpha2": "GG"},
    "248": {"name": "Isle of Man", "alpha2": "IM"},
    "249": {"name": "Jersey", "alpha2": "JE"},
    "251": {"name": "Svalbard and Jan Mayen", "alpha2": "SJ"},
    "252": {"name": "Vatican City", "alpha2": "VA"},
    "305": {"name": "Saint Barthélemy", "alpha2": "BL"},
    "306": {"name": "Saint Martin", "alpha2": "MF"},
    "307": {"name": "Sint Maarten", "alpha2": "SX"},
    "97": {"name": "British Indian Ocean Territory", "alpha2": "IO"},
    "102": {"name": "Western Sahara", "alpha2": "EH"},
}

# Mapeamento de nomes alternativos para o nome principal
country_aliases = {
    "china": "China PR",
    "chinese taipei/taiwan": "Chinese Taipei",
    "taiwan": "Chinese Taipei",
    "czechia": "Czech Republic",
    "iran": "IR Iran",
    "ireland": "Republic of Ireland",
    "north korea": "Korea DPR",
    "south korea": "Korea Republic",
    "the bahamas": "Bahamas",
    "the gambia": "Gambia",
    "united states": "USA",
    "united states of america": "USA",
    "united states virgin islands": "US Virgin Islands",
    "the comoros": "Comoros",
    "the congo": "Congo",
    "the marshall islands": "Micronesia",
    "the niger": "Niger",
    "the northern mariana islands": "Northern Mariana Islands",
    "the philippines": "Philippines",
    "the sudan": "Sudan",
    "brunei": "Brunei Darussalam",
    "cabo verde": "Cape Verde",
    "kyrgyzstan": "Kyrgyz Republic",
}

# Função para normalizar nomes de países (remove "the" e converte para minúsculas)
def normalize_country_name(name):
    name = name.lower().strip()
    if name.startswith("the "):
        name = name[4:]
    return name

# Inverte o dicionário para mapear nome do país -> código, incluindo aliases
inverted_countries = {}
for code, data in countries.items():
    # Adiciona o nome principal
    normalized_name = normalize_country_name(data["name"])
    inverted_countries[normalized_name] = code
    # Adiciona aliases, se existirem
    for alias, main_name in country_aliases.items():
        if normalize_country_name(main_name) == normalized_name:
            inverted_countries[normalize_country_name(alias)] = code

def translate_countries(input_file, output_file):
    output_lines = []
    with open(input_file, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as e:
                print(f"Linha {i} ignorada por erro JSON: {e}")
                continue
            if "Country" in obj:
                country_name = normalize_country_name(obj["Country"])
                if country_name in inverted_countries:
                    obj["Country"] = inverted_countries[country_name]
                else:
                    print(f"Linha {i}: país '{obj['Country']}' não encontrado no dicionário.")
            output_lines.append(json.dumps(obj, ensure_ascii=False))
    
    with open(output_file, 'w', encoding='utf-8') as f_out:
        for line in output_lines:
            f_out.write(line + "\n")
    
    print(f"Arquivo traduzido salvo em '{output_file}' com {len(output_lines)} linhas.")

if __name__ == "__main__":
    input_file = "teams.jsonl"  # Altere para o arquivo de entrada
    output_file = f"new_{input_file}"   # Altere para o arquivo de saída desejado
    translate_countries(input_file, output_file)